# Cloud Build Configuration for Roscoe AI Home Helper
# Supports both dev and prod deployments with environment-specific configurations

# Available substitution variables (set via gcloud):
# _ENV: dev or prod (default: prod)
# _SERVICE_NAME: roscoe-dev or roscoe-prod (default: default)

substitutions:
  _ENV: 'prod'
  _SERVICE_NAME: 'default'

steps:
  # Step 1: Install root dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    id: 'install-root'

  # Step 2: Install backend dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: 'backend'
    id: 'install-backend'
    waitFor: ['install-root']

  # Step 3: Install frontend dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: 'frontend'
    id: 'install-frontend'
    waitFor: ['install-root']

  # Step 4: Build frontend with REACT_APP_FIREBASE_CONFIG secret
  # CRITICAL: This secret must be available during build time because
  # React apps bake environment variables into the bundle at build time
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building frontend with Firebase config..."
        export REACT_APP_FIREBASE_CONFIG="$$REACT_APP_FIREBASE_CONFIG"
        cd frontend
        npm run build
        echo "Frontend build complete"
    id: 'build-frontend'
    waitFor: ['install-frontend']
    secretEnv:
      - 'REACT_APP_FIREBASE_CONFIG'

  # Step 5: Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${_ENV}" = "dev" ]; then
          echo "Deploying to DEV environment..."
          gcloud app deploy app-dev.yaml --quiet
        else
          echo "Deploying to PROD environment..."
          gcloud app deploy app.yaml --quiet
        fi
    id: 'deploy'
    waitFor: ['build-frontend', 'install-backend']

# Secret Manager Configuration
# These secrets are accessed from GCP Secret Manager
# Make sure all secrets exist and have proper IAM permissions
availableSecrets:
  secretManager:
    # Frontend secret (build-time) - injected during npm run build
    - versionName: 'projects/$PROJECT_ID/secrets/REACT_APP_FIREBASE_CONFIG/versions/latest'
      env: 'REACT_APP_FIREBASE_CONFIG'

    # Backend secrets (runtime) - injected via app.yaml at runtime
    # Note: These are NOT used in cloudbuild.yaml, they're accessed by App Engine
    # - FIREBASE_SERVICE_ACCOUNT
    # - GEMINI_API_KEY
    # - FRONTEND_URL

# Build options
options:
  # Use faster machine type for builds
  machineType: 'E2_HIGHCPU_8'

  # Enable build logging
  logging: 'CLOUD_LOGGING_ONLY'

  # Set substitution option
  substitutionOption: 'ALLOW_LOOSE'

# Build timeout (max 20 minutes)
timeout: '1200s'
