[build]
cmd = "npm run install-all && npm run build:frontend"

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
DISABLE_ESLINT_PLUGIN = "true"
CI = "false"

# Optimization settings
[phases.build]
cmds = [
  "npm ci --only=production",
  "cd frontend && npm ci --only=production",
  "cd backend && npm ci --only=production",
  "cd frontend && npm run build"
]

[phases.start]
cmd = "node backend/server.js"
